#!/usr/bin/env bash
##########################################################################
# If not stated otherwise in this file or this component's Licenses.txt
# file the following copyright and licenses apply:
#
# Copyright 2023 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

LOCAL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $LOCAL_DIR/setup-environment

echo 'Appending DISTRO_FEATURES_remove = " rdkb_cellular_manager_mm" to local.conf'
echo 'DISTRO_FEATURES_remove = " rdkb_cellular_manager_mm"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_append = " rdkb_cellular_manager" to local.conf'
echo 'DISTRO_FEATURES_append = " rdkb_cellular_manager"' >> ${BUILD_DIR}/conf/local.conf

# Remove OneWifi Distro features to enable ccsp-wifi-agent
echo 'Appending DISTRO_FEATURES_remove = " OneWifi" to local.conf'
echo 'DISTRO_FEATURES_remove = " OneWifi"' >> ${BUILD_DIR}/conf/local.conf

# Remove WanManager Distro features to enable gwprovapp
echo 'Appending DISTRO_FEATURES_remove = " rdkb_power_manager" to local.conf'
echo 'DISTRO_FEATURES_remove = " rdkb_power_manager"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_remove = " rdkb_gpon_manager" to local.conf'
echo 'DISTRO_FEATURES_remove = " rdkb_gpon_manager"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_remove = " rdkb_wan_manager" to local.conf'
echo 'DISTRO_FEATURES_remove = " rdkb_wan_manager"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_remove = " rdkb_voice_manager_dmltr104_v2" to local.conf'
echo 'DISTRO_FEATURES_remove = " rdkb_voice_manager_dmltr104_v2"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_remove = " rdkb_xdsl_ppp_manager" to local.conf'
echo 'DISTRO_FEATURES_remove = " rdkb_xdsl_ppp_manager"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_remove = " fwupgrade_manager" to local.conf'
echo 'DISTRO_FEATURES_remove = " fwupgrade_manager"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_remove = " rdkb_inter_device_manager" to local.conf'
echo 'DISTRO_FEATURES_remove = " rdkb_inter_device_manager"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_remove = " rdk_ledmanager" to local.conf'
echo 'DISTRO_FEATURES_remove = " rdk_ledmanager"' >> ${BUILD_DIR}/conf/local.conf

echo 'Appending DISTRO_FEATURES_remove = " rdk_ledmanager" to local.conf'
echo 'DISTRO_FEATURES_remove = " pm_lan_mgr"' >> ${BUILD_DIR}/conf/local.conf
